<?php


return [


    'AuthControllers@login' => 'login',
    'AuthControllers@doLogin' => 'doLogin',
    'AuthControllers@logout' => 'logout',
    'AuthControllers@register' => 'register',

    'DashboardControllers@Dashboard' => 'list-dashboard',

    'UsersControllers@index' => 'list-users',
    'UsersControllers@edit' => 'edit-user',
    'UsersControllers@update' => 'edit-user',
    'UsersControllers@fastEdit' => 'edit-user',
    'UsersControllers@add' => 'add-user',
    'UsersControllers@create' => 'add-user',
    'UsersControllers@delete' => 'delete-user',
    'UsersControllers@arrange' => 'sort-user',
    'UsersControllers@sort' => 'sort-user',
    'UsersControllers@charts' => 'charts-user',
    'UsersControllers@uploadImage' => 'uploadImage-user',
    'UsersControllers@deleteImage' => 'deleteImage-user',

    'GroupsControllers@index' => 'list-groups',
    'GroupsControllers@edit' => 'edit-group',
    'GroupsControllers@update' => 'edit-group',
    'GroupsControllers@fastEdit' => 'edit-group',
    'GroupsControllers@add' => 'add-group',
    'GroupsControllers@create' => 'add-group',
    'GroupsControllers@delete' => 'delete-group',
    'GroupsControllers@arrange' => 'sort-group',
    'GroupsControllers@sort' => 'sort-group',
    'GroupsControllers@charts' => 'charts-group',

    'CityControllers@index' => 'list-cities',
    'CityControllers@edit' => 'edit-city',
    'CityControllers@update' => 'edit-city',
    'CityControllers@fastEdit' => 'edit-city',
    'CityControllers@add' => 'add-city',
    'CityControllers@create' => 'add-city',
    'CityControllers@delete' => 'delete-city',
    'CityControllers@arrange' => 'sort-city',
    'CityControllers@sort' => 'sort-city',
    'CityControllers@charts' => 'charts-city',

    'PageControllers@index' => 'list-pages',
    'PageControllers@edit' => 'edit-page',
    'PageControllers@update' => 'edit-page',
    'PageControllers@fastEdit' => 'edit-page',
    'PageControllers@add' => 'add-page',
    'PageControllers@create' => 'add-page',
    'PageControllers@delete' => 'delete-page',
    'PageControllers@arrange' => 'sort-page',
    'PageControllers@sort' => 'sort-page',
    'PageControllers@charts' => 'charts-page',
    'PageControllers@uploadImage' => 'uploadImage-page',
    'PageControllers@deleteImage' => 'deleteImage-page',

    'ContactUsControllers@index' => 'list-contactUs',
    'ContactUsControllers@edit' => 'edit-contactUs',
    'ContactUsControllers@fastEdit' => 'edit-contactUs',
    'ContactUsControllers@update' => 'edit-contactUs',
    'ContactUsControllers@reply' => 'reply-contactUs',
    'ContactUsControllers@postReply' => 'reply-contactUs',
    'ContactUsControllers@delete' => 'delete-contactUs',
    'ContactUsControllers@charts' => 'charts-contactUs',

    'LogControllers@index' => 'list-logs',
    'LogControllers@fastEdit' => 'edit-log',
    'LogControllers@delete' => 'delete-log',
    'LogControllers@arrange' => 'sort-log',
    'LogControllers@sort' => 'sort-log',
    'LogControllers@charts' => 'charts-log',
    
    'BlockedUsersControllers@index' => 'list-blockedUsers',
    'BlockedUsersControllers@fastEdit' => 'edit-blockedUser',
    'BlockedUsersControllers@delete' => 'delete-blockedUser',
    'BlockedUsersControllers@arrange' => 'sort-blockedUser',
    'BlockedUsersControllers@sort' => 'sort-blockedUser',
    'BlockedUsersControllers@charts' => 'charts-blockedUser',

    'VariablesControllers@index' => 'list-variables',
    'VariablesControllers@update' => 'edit-variable',
    'VariablesControllers@panel' => 'list-variables2',
    'VariablesControllers@uploadImage' => 'edit-variable2',
    'VariablesControllers@deleteImage' => 'edit-variable2',

    // 'MembershipControllers@index' => 'list-memberships',
    // 'MembershipControllers@edit' => 'edit-membership',
    // 'MembershipControllers@update' => 'edit-membership',
    // 'MembershipControllers@fastEdit' => 'edit-membership',
    // 'MembershipControllers@add' => 'add-membership',
    // 'MembershipControllers@create' => 'add-membership',
    // 'MembershipControllers@delete' => 'delete-membership',
    // 'MembershipControllers@arrange' => 'sort-membership',
    // 'MembershipControllers@sort' => 'sort-membership',
    // 'MembershipControllers@charts' => 'charts-membership',

    // 'FeatureControllers@index' => 'list-features',
    // 'FeatureControllers@edit' => 'edit-feature',
    // 'FeatureControllers@update' => 'edit-feature',
    // 'FeatureControllers@fastEdit' => 'edit-feature',
    // 'FeatureControllers@add' => 'add-feature',
    // 'FeatureControllers@create' => 'add-feature',
    // 'FeatureControllers@delete' => 'delete-feature',
    // 'FeatureControllers@arrange' => 'sort-feature',
    // 'FeatureControllers@sort' => 'sort-feature',
    // 'FeatureControllers@charts' => 'charts-feature',

    // 'ConditionControllers@index' => 'list-conditions',
    // 'ConditionControllers@edit' => 'edit-condition',
    // 'ConditionControllers@update' => 'edit-condition',
    // 'ConditionControllers@fastEdit' => 'edit-condition',
    // 'ConditionControllers@add' => 'add-condition',
    // 'ConditionControllers@create' => 'add-condition',
    // 'ConditionControllers@delete' => 'delete-condition',
    // 'ConditionControllers@arrange' => 'sort-condition',
    // 'ConditionControllers@sort' => 'sort-condition',
    // 'ConditionControllers@charts' => 'charts-condition',

    'FieldControllers@index' => 'list-fields',
    'FieldControllers@edit' => 'edit-field',
    'FieldControllers@update' => 'edit-field',
    'FieldControllers@fastEdit' => 'edit-field',
    'FieldControllers@add' => 'add-field',
    'FieldControllers@create' => 'add-field',
    'FieldControllers@delete' => 'delete-field',
    'FieldControllers@arrange' => 'sort-field',
    'FieldControllers@sort' => 'sort-field',
    'FieldControllers@charts' => 'charts-field',

    'SliderControllers@index' => 'list-sliders',
    'SliderControllers@edit' => 'edit-slider',
    'SliderControllers@update' => 'edit-slider',
    'SliderControllers@fastEdit' => 'edit-slider',
    'SliderControllers@add' => 'add-slider',
    'SliderControllers@create' => 'add-slider',
    'SliderControllers@delete' => 'delete-slider',
    'SliderControllers@arrange' => 'sort-slider',
    'SliderControllers@sort' => 'sort-slider',
    'SliderControllers@charts' => 'charts-slider',
    'SliderControllers@uploadImage' => 'uploadImage-slider',
    'SliderControllers@deleteImage' => 'deleteImage-slider',


    'OrderControllers@index' => 'list-orders',
    'OrderControllers@softDelete' => 'delete-order',
    'OrderControllers@delete' => 'delete-order',
    'OrderControllers@fastEdit' => 'edit-order',
    'OrderControllers@changeStatus' => 'edit-order',
    'OrderControllers@status' => 'edit-order',
    'OrderControllers@edit' => 'edit-order',
    'OrderControllers@Update' => 'edit-order',

    'UserCardControllers@index' => 'list-user-cards',
    'UserCardControllers@fastEdit' => 'edit-user-card',
    'UserCardControllers@printCard' => 'edit-user-card',
    'UserCardControllers@viewCard' => 'edit-user-card',
    'UserCardControllers@delete' => 'delete-user-card',
    'UserCardControllers@charts' => 'charts-user-card',
    'UserCardControllers@newMember' => 'edit-user-card',

    'EventControllers@index' => 'list-events',
    'EventControllers@edit' => 'edit-event',
    'EventControllers@update' => 'edit-event',
    'EventControllers@fastEdit' => 'edit-event',
    'EventControllers@add' => 'add-event',
    'EventControllers@create' => 'add-event',
    'EventControllers@delete' => 'delete-event',
    'EventControllers@arrange' => 'sort-event',
    'EventControllers@sort' => 'sort-event',
    'EventControllers@charts' => 'charts-event',
    'EventControllers@uploadImage' => 'uploadImage-event',
    'EventControllers@deleteImage' => 'deleteImage-event',

    'CouponControllers@index' => 'list-coupons',
    'CouponControllers@edit' => 'edit-coupon',
    'CouponControllers@update' => 'edit-coupon',
    'CouponControllers@fastEdit' => 'edit-coupon',
    'CouponControllers@add' => 'add-coupon',
    'CouponControllers@create' => 'add-coupon',
    'CouponControllers@delete' => 'delete-coupon',
    'CouponControllers@arrange' => 'sort-coupon',
    'CouponControllers@sort' => 'sort-coupon',
    'CouponControllers@charts' => 'charts-coupon',

    'InitiativeControllers@index' => 'list-initiatives',
    'InitiativeControllers@edit' => 'edit-initiative',
    'InitiativeControllers@update' => 'edit-initiative',
    'InitiativeControllers@fastEdit' => 'edit-initiative',
    'InitiativeControllers@add' => 'add-initiative',
    'InitiativeControllers@create' => 'add-initiative',
    'InitiativeControllers@delete' => 'delete-initiative',
    'InitiativeControllers@arrange' => 'sort-initiative',
    'InitiativeControllers@sort' => 'sort-initiative',
    'InitiativeControllers@charts' => 'charts-initiative',
    'InitiativeControllers@uploadImage' => 'uploadImage-initiative',
    'InitiativeControllers@deleteImage' => 'deleteImage-initiative',

    'DirectorControllers@index' => 'list-directors',
    'DirectorControllers@edit' => 'edit-director',
    'DirectorControllers@update' => 'edit-director',
    'DirectorControllers@fastEdit' => 'edit-director',
    'DirectorControllers@add' => 'add-director',
    'DirectorControllers@create' => 'add-director',
    'DirectorControllers@delete' => 'delete-director',
    'DirectorControllers@arrange' => 'sort-director',
    'DirectorControllers@sort' => 'sort-director',
    'DirectorControllers@charts' => 'charts-director',
    'DirectorControllers@uploadImage' => 'uploadImage-director',
    'DirectorControllers@deleteImage' => 'deleteImage-director',

    'FounderControllers@index' => 'list-founders',
    'FounderControllers@edit' => 'edit-founder',
    'FounderControllers@update' => 'edit-founder',
    'FounderControllers@fastEdit' => 'edit-founder',
    'FounderControllers@add' => 'add-founder',
    'FounderControllers@create' => 'add-founder',
    'FounderControllers@delete' => 'delete-founder',
    'FounderControllers@arrange' => 'sort-founder',
    'FounderControllers@sort' => 'sort-founder',
    'FounderControllers@charts' => 'charts-founder',
    'FounderControllers@uploadImage' => 'uploadImage-founder',
    'FounderControllers@deleteImage' => 'deleteImage-founder',

    'RegulationControllers@index' => 'list-regulations',
    'RegulationControllers@edit' => 'edit-regulation',
    'RegulationControllers@update' => 'edit-regulation',
    'RegulationControllers@fastEdit' => 'edit-regulation',
    'RegulationControllers@add' => 'add-regulation',
    'RegulationControllers@create' => 'add-regulation',
    'RegulationControllers@delete' => 'delete-regulation',
    'RegulationControllers@arrange' => 'sort-regulation',
    'RegulationControllers@sort' => 'sort-regulation',
    'RegulationControllers@charts' => 'charts-regulation',
    'RegulationControllers@uploadImage' => 'uploadImage-regulation',
    'RegulationControllers@deleteImage' => 'deleteImage-regulation',
  
];
